# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['buz_no', 'class_kind'], 'verbose_name_plural': 'faqs'},
        ),
        migrations.AlterField(
            model_name='faq',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
