# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20160925_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='owner',
            field=models.CharField(max_length=20, null=True, verbose_name='Owner.'),
        ),
    ]
