# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_auto_20160925_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['-mdate'], 'verbose_name_plural': 'faqs'},
        ),
    ]
