# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_auto_20160925_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='buz_no',
            new_name='buz_id',
        ),
    ]
