# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='reply',
            field=models.TextField(null=True, verbose_name='Reply.'),
        ),
    ]
